import { getThemeColors } from './theme';

const getStyles = (isDark) => {
  const t = getThemeColors(isDark);

  return {
    card: {
      background: t.surface,
      border: `1px solid ${t.border}`,
      borderRadius: '14px',
      padding: '20px',
      boxShadow: t.shadow.sm,
    },
    cardHover: {
      background: t.surface,
      border: `1px solid ${t.border}`,
      borderRadius: '14px',
      padding: '20px',
      boxShadow: t.shadow.sm,
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },
    cardFlat: {
      background: t.surface,
      border: 'none',
      borderRadius: '14px',
      padding: '20px',
    },
    section: {
      marginBottom: '14px',
    },
    btn: {
      padding: '10px 20px',
      borderRadius: '10px',
      border: 'none',
      fontWeight: 600,
      fontSize: '13px',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '6px',
      transition: 'all 0.15s ease',
    },
    btnPrimary: (isDark) => ({
      padding: '10px 20px',
      borderRadius: '10px',
      border: 'none',
      background: t.gradient.primary,
      color: '#fff',
      fontWeight: 700,
      fontSize: '13px',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '6px',
      boxShadow: t.shadow.glowSm,
      transition: 'all 0.15s ease',
    }),
    btnSuccess: {
      padding: '10px 20px',
      borderRadius: '10px',
      border: 'none',
      background: t.gradient.success,
      color: '#fff',
      fontWeight: 700,
      fontSize: '13px',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '6px',
      boxShadow: '0 4px 14px rgba(16,185,129,0.3)',
      transition: 'all 0.15s ease',
    },
    btnDanger: {
      padding: '10px 20px',
      borderRadius: '10px',
      border: 'none',
      background: t.gradient.danger,
      color: '#fff',
      fontWeight: 700,
      fontSize: '13px',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '6px',
      boxShadow: '0 4px 14px rgba(239,68,68,0.3)',
      transition: 'all 0.15s ease',
    },
    btnOutline: {
      padding: '10px 20px',
      borderRadius: '10px',
      border: `1px solid ${t.border}`,
      background: 'transparent',
      color: t.text,
      fontWeight: 600,
      fontSize: '13px',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '6px',
      transition: 'all 0.15s ease',
    },
    btnSm: {
      padding: '6px 12px',
      borderRadius: '8px',
      border: 'none',
      fontWeight: 600,
      fontSize: '12px',
      cursor: 'pointer',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '4px',
      transition: 'all 0.15s ease',
    },
    btnIcon: {
      width: '38px',
      height: '38px',
      borderRadius: '10px',
      border: `1px solid ${t.border}`,
      background: t.surface,
      color: t.textSecondary,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'all 0.15s ease',
    },
    input: {
      padding: '10px 14px',
      borderRadius: '10px',
      border: `1px solid ${t.border}`,
      background: t.surface,
      color: t.text,
      fontSize: '13px',
      outline: 'none',
      width: '100%',
      boxSizing: 'border-box',
    },
    inputGroup: {
      display: 'flex',
      alignItems: 'center',
      gap: '0',
      position: 'relative',
    },
    badge: (color = t.primary) => ({
      padding: '3px 8px',
      borderRadius: '6px',
      background: color + '18',
      color: color,
      fontSize: '11px',
      fontWeight: 600,
      display: 'inline-block',
    }),
    badgeSuccess: {
      padding: '3px 10px',
      borderRadius: '6px',
      background: t.badge.success.bg,
      color: t.badge.success.color,
      fontSize: '11px',
      fontWeight: 600,
    },
    badgeWarning: {
      padding: '3px 10px',
      borderRadius: '6px',
      background: t.badge.warning.bg,
      color: t.badge.warning.color,
      fontSize: '11px',
      fontWeight: 600,
    },
    badgeDanger: {
      padding: '3px 10px',
      borderRadius: '6px',
      background: t.badge.danger.bg,
      color: t.badge.danger.color,
      fontSize: '11px',
      fontWeight: 600,
    },
    statCard: {
      background: t.surface,
      border: `1px solid ${t.border}`,
      borderRadius: '14px',
      padding: '18px 20px',
      position: 'relative',
      overflow: 'hidden',
      boxShadow: t.shadow.sm,
    },
    statCardAccent: (color) => ({
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '3px',
      background: `linear-gradient(90deg, ${color}, transparent)`,
    }),
    pageTitle: {
      fontSize: '20px',
      fontWeight: 700,
      color: t.text,
      letterSpacing: '-0.3px',
      margin: '0 0 18px 0',
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
    },
    sectionTitle: {
      fontSize: '16px',
      fontWeight: 600,
      color: t.text,
      margin: '0 0 12px 0',
    },
    textBody: {
      fontSize: '14px',
      color: t.text,
      fontWeight: 500,
      lineHeight: 1.5,
    },
    textSmall: {
      fontSize: '12px',
      color: t.textSecondary,
      fontWeight: 500,
    },
    textMicro: {
      fontSize: '11px',
      color: t.textSecondary,
      fontWeight: 500,
    },
    textMuted: {
      color: t.textSecondary,
    },
    divider: {
      border: 'none',
      borderTop: `1px solid ${t.border}`,
      margin: '12px 0',
    },
    emptyState: {
      textAlign: 'center',
      padding: '48px 20px',
    },
    emptyIcon: (color = t.textSecondary) => ({
      opacity: 0.25,
      color: color,
      marginBottom: '12px',
    }),
    emptyTitle: {
      fontSize: '15px',
      fontWeight: 600,
      color: t.text,
      margin: '0 0 4px',
    },
    emptyText: {
      fontSize: '13px',
      color: t.textSecondary,
      margin: '0 0 16px',
    },
    modal: {
      background: t.surface,
      borderRadius: '18px',
      padding: '28px',
      maxWidth: '500px',
      width: '90%',
      border: `1px solid ${t.border}`,
      boxShadow: t.shadow.lg,
    },
    modalSm: {
      background: t.surface,
      borderRadius: '18px',
      padding: '24px',
      maxWidth: '420px',
      width: '90%',
      border: `1px solid ${t.border}`,
      boxShadow: t.shadow.xl,
    },
    modalOverlay: {
      position: 'fixed',
      inset: 0,
      zIndex: 1000,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: isDark ? 'rgba(0,0,0,0.6)' : 'rgba(0,0,0,0.3)',
      backdropFilter: 'blur(4px)',
      padding: '20px',
    },
    toast: {
      position: 'fixed',
      top: '20px',
      right: '20px',
      zIndex: 9999,
      background: t.success,
      color: '#fff',
      padding: '10px 18px',
      borderRadius: '10px',
      fontWeight: 600,
      fontSize: '13px',
      boxShadow: t.shadow.md,
    },
    table: {
      width: '100%',
      borderCollapse: 'collapse',
    },
    tableHeader: {
      padding: '10px 14px',
      textAlign: 'left',
      fontSize: '11px',
      fontWeight: 600,
      color: t.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: '0.5px',
      borderBottom: `1px solid ${t.border}`,
    },
    tableCell: {
      padding: '12px 14px',
      fontSize: '13px',
      color: t.text,
      borderBottom: `1px solid ${t.border}`,
    },
    flexRow: (gap = '10px') => ({
      display: 'flex',
      alignItems: 'center',
      gap,
    }),
    flexBetween: (gap = '10px') => ({
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap,
    }),
    flexCol: (gap = '10px') => ({
      display: 'flex',
      flexDirection: 'column',
      gap,
    }),
    gridAuto: (minWidth = '280px', gap = '14px') => ({
      display: 'grid',
      gridTemplateColumns: `repeat(auto-fit, minmax(${minWidth}, 1fr))`,
      gap,
    }),
    skeleton: {
      background: isDark ? '#334155' : '#e2e8f0',
      borderRadius: '10px',
      animation: 'shimmer 1.5s infinite',
    },

    t,
  };
};

export default getStyles;
